name: Deploy Laravel to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Setup PHP + Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}
          restore-keys: composer-

      - name: Install dependencies
        run: |
          composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist
        env:
          COMPOSER_MEMORY_LIMIT: -1

      - name: Buat file .env dari GitHub Secret
        run: echo "${{ secrets.LARAVEL_ENV_FILE }}" > .env

      - name: Siapkan folder untuk upload
        run: |
          mkdir deploy
          rsync -av --exclude=public ./ deploy/
          mkdir -p deploy/htdocs
          cp -r public/* deploy/htdocs/
          sed -i "s|../vendor/autoload.php|../vendor/autoload.php|g" deploy/htdocs/index.php
          sed -i "s|../bootstrap/app.php|../bootstrap/app.php|g" deploy/htdocs/index.php

      - name: Upload ke InfinityFree
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /testing-chandra.ct.ws/
          local-dir: deploy/
